name: 'container-build-push'
description: 'Build and push Docker image'
inputs:
  # dockerfile:
  #   required: false
  #   default: ./Dockerfile
  npm-auth-token:
    required: true
  artifact_aws_region:
    required: true
  artifact_aws_role: 
    required: true
  path: 
    required: true
  working_dir:
    required: true
    default: ${{ github.workspace }}
  # service:
  #   required: true
outputs:
  image-name:
    description: "Container image name"
    value: ${{ steps.image-name.outputs.image-name }}
runs:
  using: "composite"
  steps:
    - id: package
      uses: codex-team/action-nodejs-package-info@v1.1
      with:
        path: "${{ inputs.working_dir }}/${{ inputs.path }}" 
        
    - uses: rlespinasse/github-slug-action@v4
    
    - id: image-name
      shell: bash
      run: |
        RANDOM_NUMBER=$(shuf -i 1000-9999 -n 1)
        # with regex remove @ and / from package name
        PACKAGE_NAME_CLEAN=`sed -E 's/@//g; s/\//-/g' <<< "${{ steps.package.outputs.name }}"`
        echo "image-name=${PACKAGE_NAME_CLEAN}-${{ env.GITHUB_REF_SLUG }}-${{ steps.package.outputs.version }}.${{ github.run_number }}.${RANDOM_NUMBER}" >> $GITHUB_OUTPUT

    - name: Configure DEV AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ inputs.artifact_aws_region }}
        role-session-name: artifactSession-${{ github.run_id }}-${{ github.run_attempt }}-${{ github.job }}
        role-to-assume: ${{ inputs.artifact_aws_role }}
        role-duration-seconds: 3600

    - name: Setup isolated Docker config and login to ECR
      id: setup-docker
      shell: bash
      run: |
        set -e
        DOCKER_CONFIG_PATH="${{ inputs.working_dir }}/.docker-config-${{ github.run_id }}-${{ github.run_attempt }}-${{ github.job }}"

        echo "Creating Docker config directory: ${DOCKER_CONFIG_PATH}"
        mkdir -p "${DOCKER_CONFIG_PATH}"

        if [ ! -d "${DOCKER_CONFIG_PATH}" ]; then
          echo "ERROR: Failed to create Docker config directory"
          exit 1
        fi

        echo "DOCKER_CONFIG=${DOCKER_CONFIG_PATH}" >> $GITHUB_ENV

        # Get registry details
        AWS_ACCOUNT_ID=$(echo "${{ inputs.artifact_aws_role }}" | cut -d':' -f5)
        REGISTRY="${AWS_ACCOUNT_ID}.dkr.ecr.${{ inputs.artifact_aws_region }}.amazonaws.com"
        echo "registry=${REGISTRY}" >> $GITHUB_OUTPUT

        # Login to ECR with retry logic (credential helpers are unreliable with buildx)
        echo "Logging in to ECR: ${REGISTRY}"
        MAX_RETRIES=3
        RETRY_COUNT=0

        while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
          if aws ecr get-login-password --region ${{ inputs.artifact_aws_region }} | \
             docker --config "${DOCKER_CONFIG_PATH}" login --username AWS --password-stdin "${REGISTRY}"; then
            echo "Successfully logged in to ECR"
            break
          else
            RETRY_COUNT=$((RETRY_COUNT + 1))
            if [ $RETRY_COUNT -lt $MAX_RETRIES ]; then
              echo "Login failed, attempt $RETRY_COUNT of $MAX_RETRIES. Retrying in 5 seconds..."
              sleep 5
            else
              echo "ERROR: Failed to login to ECR after $MAX_RETRIES attempts"
              exit 1
            fi
          fi
        done

        echo "Verifying config.json was created:"
        ls -la "${DOCKER_CONFIG_PATH}/"
        if [ -f "${DOCKER_CONFIG_PATH}/config.json" ]; then
          echo "config.json exists"
        else
          echo "ERROR: config.json was not created by docker login"
          exit 1
        fi

        echo "Docker config setup and ECR login complete for job ${{ github.job }}"

    - name: Build and push Docker image
      shell: bash
      env:
        REGISTRY: ${{ steps.setup-docker.outputs.registry }}
        REPOSITORY: ed_services
        IMAGE_TAG: ${{ steps.image-name.outputs.image-name }}
        DOCKER_CONFIG: ${{ env.DOCKER_CONFIG }}
        AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ env.AWS_SESSION_TOKEN }}
        AWS_REGION: ${{ inputs.artifact_aws_region }}
        AWS_DEFAULT_REGION: ${{ inputs.artifact_aws_region }}
      run: |
        set -e
        export DOCKER_CONFIG="${DOCKER_CONFIG}"
        echo "Using Docker config: ${DOCKER_CONFIG}"

        # Function to ensure we're logged in
        ensure_logged_in() {
          if [ ! -d "${DOCKER_CONFIG}" ]; then
            echo "WARNING: Docker config directory was deleted, recreating..."
            mkdir -p "${DOCKER_CONFIG}"
          fi

          if [ ! -f "${DOCKER_CONFIG}/config.json" ]; then
            echo "WARNING: config.json missing, logging in to ECR..."
            aws ecr get-login-password --region ${AWS_REGION} | \
              docker --config "${DOCKER_CONFIG}" login --username AWS --password-stdin "${REGISTRY}"
            echo "Re-login complete"
          fi
        }

        # Determine Dockerfile path
        if [ -f ${{ inputs.path}}/Dockerfile ]; then
          DOCKERFILE=${{ inputs.path}}/Dockerfile
        else
          DOCKERFILE=./Dockerfile
        fi

        # Build image
        echo "Building image: ${REGISTRY}/${REPOSITORY}:${IMAGE_TAG}"
        docker --config "${DOCKER_CONFIG}" build -t ${REGISTRY}/${REPOSITORY}:${IMAGE_TAG} \
          --build-arg NPM_AUTH_TOKEN=${{ inputs.npm-auth-token }} \
          --build-arg SERVICE_PATH=${{ inputs.path }} \
          -f "$DOCKERFILE" .
        echo "Build complete"

        # Ensure we're still logged in after build (directory might have been deleted)
        ensure_logged_in

        # Push image with retry logic
        echo "Pushing image: ${REGISTRY}/${REPOSITORY}:${IMAGE_TAG}"
        MAX_RETRIES=3
        RETRY_COUNT=0

        while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
          if docker --config "${DOCKER_CONFIG}" push ${REGISTRY}/${REPOSITORY}:${IMAGE_TAG}; then
            echo "Push successful"
            break
          else
            RETRY_COUNT=$((RETRY_COUNT + 1))
            if [ $RETRY_COUNT -lt $MAX_RETRIES ]; then
              echo "Push failed, attempt $RETRY_COUNT of $MAX_RETRIES"
              echo "Re-authenticating and retrying in 5 seconds..."
              sleep 5
              ensure_logged_in
            else
              echo "ERROR: Failed to push image after $MAX_RETRIES attempts"
              exit 1
            fi
          fi
        done

        echo "Push complete for job ${{ github.job }}"
      working-directory: ${{ inputs.working_dir }}

    - name: Cleanup isolated Docker config
      shell: bash
      if: always()
      run: |
        DOCKER_CONFIG_PATH="${{ inputs.working_dir }}/.docker-config-${{ github.run_id }}-${{ github.run_attempt }}-${{ github.job }}"
        if [ -d "${DOCKER_CONFIG_PATH}" ]; then
          echo "Cleaning up Docker config directory: ${DOCKER_CONFIG_PATH}"
          rm -rf "${DOCKER_CONFIG_PATH}"
          echo "Cleanup complete"
        else
          echo "Docker config directory already removed: ${DOCKER_CONFIG_PATH}"
        fi

