name: 'container-build-push'
description: 'Build and push Docker image'
inputs:
  # dockerfile:
  #   required: false
  #   default: ./Dockerfile
  npm-auth-token:
    required: true
  artifact_aws_region:
    required: true
  artifact_aws_role: 
    required: true
  path: 
    required: true
  working_dir:
    required: true
    default: ${{ github.workspace }}
  # service:
  #   required: true
outputs:
  image-name:
    description: "Container image name"
    value: ${{ steps.image-name.outputs.image-name }}
runs:
  using: "composite"
  steps:
    - id: package
      uses: codex-team/action-nodejs-package-info@v1.1
      with:
        path: "${{ inputs.working_dir }}/${{ inputs.path }}" 
        
    - uses: rlespinasse/github-slug-action@v4
    
    - id: image-name
      shell: bash
      run: |
        RANDOM_NUMBER=$(shuf -i 1000-9999 -n 1)
        # with regex remove @ and / from package name
        PACKAGE_NAME_CLEAN=`sed -E 's/@//g; s/\//-/g' <<< "${{ steps.package.outputs.name }}"`
        echo "image-name=${PACKAGE_NAME_CLEAN}-${{ env.GITHUB_REF_SLUG }}-${{ steps.package.outputs.version }}.${{ github.run_number }}.${RANDOM_NUMBER}" >> $GITHUB_OUTPUT

    - name: Configure DEV AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ inputs.artifact_aws_region }}
        role-session-name: artifactSession-${{ github.run_id }}-${{ github.run_attempt }}-${{ github.job }}
        role-to-assume: ${{ inputs.artifact_aws_role }}
        role-duration-seconds: 3600

    - name: Setup isolated Docker config with ECR credential helper
      id: setup-docker
      shell: bash
      run: |
        set -e
        DOCKER_CONFIG_PATH="${{ inputs.working_dir }}/.docker-config-${{ github.run_id }}-${{ github.run_attempt }}-${{ github.job }}"

        echo "Creating Docker config directory: ${DOCKER_CONFIG_PATH}"
        mkdir -p "${DOCKER_CONFIG_PATH}"

        if [ ! -d "${DOCKER_CONFIG_PATH}" ]; then
          echo "ERROR: Failed to create Docker config directory"
          exit 1
        fi

        echo "DOCKER_CONFIG=${DOCKER_CONFIG_PATH}" >> $GITHUB_ENV

        # Get registry details
        AWS_ACCOUNT_ID=$(echo "${{ inputs.artifact_aws_role }}" | cut -d':' -f5)
        REGISTRY="${AWS_ACCOUNT_ID}.dkr.ecr.${{ inputs.artifact_aws_region }}.amazonaws.com"
        echo "registry=${REGISTRY}" >> $GITHUB_OUTPUT

        # Configure Docker to use ECR credential helper instead of static credentials
        echo "Creating config.json with credential helper configuration..."
        echo "DEBUG: Writing to ${DOCKER_CONFIG_PATH}/config.json"
        echo "DEBUG: Directory permissions:"
        ls -la "${DOCKER_CONFIG_PATH}"

        echo '{' > "${DOCKER_CONFIG_PATH}/config.json" || { echo "ERROR: Failed to write to config.json (line 1)"; exit 1; }
        echo '  "credHelpers": {' >> "${DOCKER_CONFIG_PATH}/config.json" || { echo "ERROR: Failed to append to config.json (line 2)"; exit 1; }
        echo '    "REGISTRY_PLACEHOLDER": "ecr-login"' >> "${DOCKER_CONFIG_PATH}/config.json" || { echo "ERROR: Failed to append to config.json (line 3)"; exit 1; }
        echo '  }' >> "${DOCKER_CONFIG_PATH}/config.json" || { echo "ERROR: Failed to append to config.json (line 4)"; exit 1; }
        echo '}' >> "${DOCKER_CONFIG_PATH}/config.json" || { echo "ERROR: Failed to append to config.json (line 5)"; exit 1; }

        echo "DEBUG: File after write:"
        ls -la "${DOCKER_CONFIG_PATH}/config.json" || { echo "ERROR: config.json does not exist after write!"; exit 1; }

        if [ ! -f "${DOCKER_CONFIG_PATH}/config.json" ]; then
          echo "ERROR: Failed to create config.json"
          exit 1
        fi

        echo "DEBUG: Running sed to replace placeholder..."
        sed -i "s|REGISTRY_PLACEHOLDER|${REGISTRY}|g" "${DOCKER_CONFIG_PATH}/config.json" || { echo "ERROR: sed failed"; exit 1; }

        echo "DEBUG: File after sed:"
        ls -la "${DOCKER_CONFIG_PATH}/config.json"

        echo "Verifying config.json content:"
        cat "${DOCKER_CONFIG_PATH}/config.json"
        echo "Docker config setup complete for job ${{ github.job }}"

    - name: Build and push Docker image
      shell: bash
      env:
        REGISTRY: ${{ steps.setup-docker.outputs.registry }}
        REPOSITORY: ed_services
        IMAGE_TAG: ${{ steps.image-name.outputs.image-name }}
        DOCKER_CONFIG: ${{ env.DOCKER_CONFIG }}
        AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ env.AWS_SESSION_TOKEN }}
        AWS_REGION: ${{ inputs.artifact_aws_region }}
        AWS_DEFAULT_REGION: ${{ inputs.artifact_aws_region }}
      run: |
        export DOCKER_CONFIG="${DOCKER_CONFIG}"
        echo "Using Docker config: ${DOCKER_CONFIG}"

        # Debug: Check if config directory and file exist
        echo "DEBUG: Checking if config directory exists..."
        ls -la "${DOCKER_CONFIG}" || echo "ERROR: Directory does not exist!"

        echo "DEBUG: Checking if config.json exists..."
        if [ -f "${DOCKER_CONFIG}/config.json" ]; then
          echo "DEBUG: config.json found, contents:"
          cat "${DOCKER_CONFIG}/config.json"
        else
          echo "ERROR: config.json NOT FOUND at ${DOCKER_CONFIG}/config.json"
          exit 1
        fi

        echo "DEBUG: Current docker context:"
        docker context ls

        echo "DEBUG: Docker buildx builder info:"
        docker buildx ls

        if [ -f ${{ inputs.path}}/Dockerfile ]; then
          DOCKERFILE=${{ inputs.path}}/Dockerfile
        else
          DOCKERFILE=./Dockerfile
        fi

        echo "Building image: ${REGISTRY}/${REPOSITORY}:${IMAGE_TAG}"
        docker --config "${DOCKER_CONFIG}" build -t ${REGISTRY}/${REPOSITORY}:${IMAGE_TAG} \
          --build-arg NPM_AUTH_TOKEN=${{ inputs.npm-auth-token }} \
          --build-arg SERVICE_PATH=${{ inputs.path }} \
          -f "$DOCKERFILE" .

        echo "Build complete, checking if config.json still exists..."
        echo "DEBUG: Checking DOCKER_CONFIG directory after build:"
        ls -la "${DOCKER_CONFIG}/" || echo "ERROR: DOCKER_CONFIG directory disappeared!"

        if [ ! -f "${DOCKER_CONFIG}/config.json" ]; then
          echo "ERROR: config.json was DELETED during docker build!"
          echo "This explains why push fails with 'no basic auth credentials'"
          echo "Attempting to recreate with explicit docker login..."

          # Use docker login instead of credential helper since that's more reliable
          aws ecr get-login-password --region ${AWS_REGION} | \
            docker --config "${DOCKER_CONFIG}" login --username AWS --password-stdin "${REGISTRY}"

          echo "Recreated config.json via docker login:"
          cat "${DOCKER_CONFIG}/config.json"
        else
          echo "DEBUG: config.json still exists after build"
          cat "${DOCKER_CONFIG}/config.json"
        fi

        echo "Pushing image..."
        docker --config "${DOCKER_CONFIG}" push ${REGISTRY}/${REPOSITORY}:${IMAGE_TAG}

        echo "Push complete for job ${{ github.job }}"
      working-directory: ${{ inputs.working_dir }}

    - name: Cleanup isolated Docker config
      shell: bash
      if: always()
      run: |
        DOCKER_CONFIG_PATH="${{ inputs.working_dir }}/.docker-config-${{ github.run_id }}-${{ github.run_attempt }}-${{ github.job }}"
        if [ -d "${DOCKER_CONFIG_PATH}" ]; then
          echo "Cleaning up Docker config directory: ${DOCKER_CONFIG_PATH}"
          rm -rf "${DOCKER_CONFIG_PATH}"
          echo "Cleanup complete"
        else
          echo "Docker config directory already removed: ${DOCKER_CONFIG_PATH}"
        fi

