name: 'container-build-push'
description: 'Build and push Docker image'
inputs:
  # dockerfile:
  #   required: false
  #   default: ./Dockerfile
  npm-auth-token:
    required: true
  artifact_aws_region:
    required: true
  artifact_aws_role: 
    required: true
  path: 
    required: true
  working_dir:
    required: true
    default: ${{ github.workspace }}
  # service:
  #   required: true
outputs:
  image-name:
    description: "Container image name"
    value: ${{ steps.image-name.outputs.image-name }}
runs:
  using: "composite"
  steps:
    - id: package
      uses: codex-team/action-nodejs-package-info@v1.1
      with:
        path: "${{ inputs.working_dir }}/${{ inputs.path }}" 
        
    - uses: rlespinasse/github-slug-action@v4
    
    - id: image-name
      shell: bash
      run: |
        RANDOM_NUMBER=$(shuf -i 1000-9999 -n 1)
        # with regex remove @ and / from package name
        PACKAGE_NAME_CLEAN=`sed -E 's/@//g; s/\//-/g' <<< "${{ steps.package.outputs.name }}"`
        echo "image-name=${PACKAGE_NAME_CLEAN}-${{ env.GITHUB_REF_SLUG }}-${{ steps.package.outputs.version }}.${{ github.run_number }}.${RANDOM_NUMBER}" >> $GITHUB_OUTPUT

    - name: Configure DEV AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ inputs.artifact_aws_region }}
        role-session-name: artifactSession-${{ github.run_id }}-${{ github.run_attempt }}-${{ github.job }}
        role-to-assume: ${{ inputs.artifact_aws_role }}
        role-duration-seconds: 3600

    - name: Setup isolated Docker config with ECR credential helper
      id: setup-docker
      shell: bash
      run: |
        DOCKER_CONFIG_PATH="${{ inputs.working_dir }}/.docker-config-${{ github.run_id }}-${{ github.run_attempt }}-${{ github.job }}"
        mkdir -p "${DOCKER_CONFIG_PATH}"
        echo "DOCKER_CONFIG=${DOCKER_CONFIG_PATH}" >> $GITHUB_ENV

        # Get registry details
        AWS_ACCOUNT_ID=$(echo "${{ inputs.artifact_aws_role }}" | cut -d':' -f5)
        REGISTRY="${AWS_ACCOUNT_ID}.dkr.ecr.${{ inputs.artifact_aws_region }}.amazonaws.com"
        echo "registry=${REGISTRY}" >> $GITHUB_OUTPUT

        # Configure Docker to use ECR credential helper instead of static credentials
        cat > "${DOCKER_CONFIG_PATH}/config.json" <<EOF
        {
          "credHelpers": {
            "${REGISTRY}": "ecr-login"
          }
        }
        EOF

        echo "Docker config created with ECR credential helper at: ${DOCKER_CONFIG_PATH}"
        echo "Registry: ${REGISTRY}"

    - name: Build and push Docker image
      shell: bash
      env:
        REGISTRY: ${{ steps.setup-docker.outputs.registry }}
        REPOSITORY: ed_services
        IMAGE_TAG: ${{ steps.image-name.outputs.image-name }}
        DOCKER_CONFIG: ${{ env.DOCKER_CONFIG }}
      run: |
        export DOCKER_CONFIG="${DOCKER_CONFIG}"
        echo "Using Docker config: ${DOCKER_CONFIG}"

        if [ -f ${{ inputs.path}}/Dockerfile ]; then
          DOCKERFILE=${{ inputs.path}}/Dockerfile
        else
          DOCKERFILE=./Dockerfile
        fi

        echo "Building image: ${REGISTRY}/${REPOSITORY}:${IMAGE_TAG}"
        docker --config "${DOCKER_CONFIG}" build -t ${REGISTRY}/${REPOSITORY}:${IMAGE_TAG} \
          --build-arg NPM_AUTH_TOKEN=${{ inputs.npm-auth-token }} \
          --build-arg SERVICE_PATH=${{ inputs.path }} \
          -f "$DOCKERFILE" .

        echo "Build complete, pushing image..."
        docker --config "${DOCKER_CONFIG}" push ${REGISTRY}/${REPOSITORY}:${IMAGE_TAG}

        echo "Push complete for job ${{ github.job }}"
      working-directory: ${{ inputs.working_dir }}
        
